package main

import (
	"crypto/tls"
	"crypto/x509"
	"log"
	"net/http"
)

// extraCAs 是标准 CA 包可能缺失的根证书（如中国 TrustAsia）。
// 当容器使用 scratch 基础镜像时，系统 CA 池为空，这些证书提供 TLS 验证能力。
// 来源：curl.se/ca/cacert.pem（Mozilla CA 包，BSD 授权）+
//
//	TrustAsia TLS RSA Root CA（open.bigmodel.cn 等国产 API 需要）
const extraCAs = `
-----BEGIN CERTIFICATE-----
MIIF/TCCBOWgAwIBAgIRALLcTDSTLXCc1L8LCZQBaVwwDQYJKoZIhvcNAQEMBQAw
fjELMAkGA1UEBhMCUEwxIjAgBgNVBAoTGVVuaXpldG8gVGVjaG5vbG9naWVzIFMu
QS4xJzAlBgNVBAsTHkNlcnR1bSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEiMCAG
A1UEAxMZQ2VydHVtIFRydXN0ZWQgTmV0d29yayBDQTAeFw0yNTEwMDcwNjU3MDha
Fw0yOTAxMTQwNjU3MDhaMFgxCzAJBgNVBAYTAkNOMSUwIwYDVQQKExxUcnVzdEFz
aWEgVGVjaG5vbG9naWVzLCBJbmMuMSIwIAYDVQQDExlUcnVzdEFzaWEgVExTIFJT
QSBSb290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwxa4G2qk
RHPl1k70uc9bC8HRmoH1Y7CPQ8G7CFoaeuEHdiYfj2lWvv42YNAMg82U6ufFLVwv
BRYCngqoL+VgJlSW+JhAHayunXRnL1T7lGOY4yZKg8aVtglDUM0Nfd5EDmAST1s1
vb+ZOG19bNriaHMf+TGlGRBzBSrDMhmF6jSq3UIeMI0/nrUeYdVvvQBycq0SP6qm
SXPyhhWVDBBfUWTO/3e4yW2s5dWY8ZkubOPJRPm1QycITfZ+3kR5u7KMHNrTS2wu
1sN4t0zVpOTa3IqODv8Pw6ZgJijPNr/6VwrsWz/pMBZ7xNvE1GSgMPvl/R1xkt0p
j0FY3gCtOv09fBqosRfwTjR4WCXWhSHreR3Q3KvPYjywx5eL1tCf0/483sXj/DqD
cIQhHQnCofy7KCFlU2B6kG2WOFv/8dd6W23TyXBJSrodOtBQ2jIgGeSLP+vVFiY3
PPt1nrAHcLgUYHfc9g9cUgq8XW2NUQraxRjIm23csIOzf6NOeEyYJavyfi4gXoIV
ptbYj6zlzTKGyPnk2oniOz6TxRNq/8f3GPxnte8YLFSrQNNsTe3FyLc4T2TElExP
oM2upcYnJXUnbcbanI6wBZnVKBHFIdS4/MeWq0pkWWFrE/xLzJKmD6RRvw5YkNmC
gzmmX7P6bpKzzTMOhajxKdOrWa3W297UK4ECAwEAAaOCAZowggGWMHUGCCsGAQUF
BwEBBGkwZzA7BggrBgEFBQcwAoYvaHR0cDovL3RydXN0YXNpYS5yZXBvc2l0b3J5
LmNlcnR1bS5wbC9jdG5jYS5jZXIwKAYIKwYBBQUHMAGGHGh0dHA6Ly9zdWJjYS5v
Y3NwLWNlcnR1bS5jb20wHwYDVR0jBBgwFoAUCHbNywf/JPbFze27kLzihDdGdfcw
EgYDVR0TAQH/BAgwBgEB/wIBAjBtBgNVHR8EZjBkMDKgMKAuhixodHRwOi8vY2Vy
dHVtLWNybC53dC50cnVzdGFzaWEuY29tL2N0bmNhLmNybDAuoCygKoYoaHR0cDov
L3RydXN0YXNpYS5jcmwuY2VydHVtLnBsL2N0bmNhLmNybDATBgNVHSUEDDAKBggr
BgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwNQYDVR0gBC4wLDAIBgZngQwBAgEwCAYG
Z4EMAQICMAcGBWeBDAEBMA0GCysGAQQBgttOAgEBMB0GA1UdDgQWBBS4B5F5XAb0
Rv17WcpaJpGnRSv4UzANBgkqhkiG9w0BAQwFAAOCAQEAIf2vyzSuFzECCTH3LPB/
bmUH1aXbVm8zVwxof+4tn8EsNYH8CgM2AHxRkXP5jOitqylySAuVIATJLYFmBQJO
XMCgf9NbbuG8P1VgnUQuUhQMChp2zT946Y55xZVANGg4o2+orw4SpclSy/R7eayX
Lccr++uqke9gJlX3FCpi4Sa8sg/kSfSv4p7tuwu4YAk+XPBew3jQc9wueAJwQ/Rz
H4LtICrekL0QuNHb0BhPcn4qELBF6f+IrOBA2MKw1m0C9y6uO8K+xd1JMpG0/RYZ
cGIH+rR5fBymQSNuD+F5I2PeXMPpigPcEdOi/NWZcCLncJLDrEU62T8hkif6MQ4F
Dw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIB9DCCAZygAwIBAgIUMbR0CTc/6k2bFqpwCDZszxG8X1swCgYIKoZIzj0EAwQw
SzELMAkGA1UEBhMCQ04xHDAaBgNVBAoTE2lUcnVzQ2hpbmEgQ28uLEx0ZC4xHjAc
BgNVBAMMFWlUcnVzQ2hpbmEgUm9vdCAoU00yKTAeFw0yMzExMjEwNjE2NDVaFw0y
OTEyMTEwNjE2NDRaMEsxCzAJBgNVBAYTAkNOMRwwGgYDVQQKExNpVHJ1c0NoaW5h
IENvLixMdGQuMR4wHAYDVQQDDBVpVHJ1c0NoaW5hIFJvb3QgKFNtMikwWTATBgcq
hkjOPQIBBggqgRzPVQGCLQNCAARFnBi9W0/6GCp2HR7Mb5yQGBPEpWFmPST4YJMU
Cjw7W5P6FWF6b9pbYMBJE4cr/F4WN+qGLDslo0OZAYFP0eTgo1MwUTAPBgNVHRMB
Af8EBTADAQH/MB0GA1UdDgQWBBSs+Ys2NfZ+5w3/FTd/LKIFex7TkDAfBgNVHSME
GDAWgBSs+Ys2NfZ+5w3/FTd/LKIFex7TkDAKBggqhkjOPQQDBAOBiwAwgYUCQU5b
QOGYGjkYn1I3VEFGG5n9A8Z5v8Wb0O3vL79dZZBD5vASOzxWYZbubHL+OZSMBNUc
SEy+5FCF3oQ7CRUEFfECQQyLO7w3VS4eRJ/mBUPJNF3GdEWGJQKxNsbj5QSNvRbc
FqVNm3rXhFfGe4SR8slW2V/RvP/MTrgcmfjJmAQMXIPe
-----END CERTIFICATE-----
`

// init 将补充的 CA 证书加载到系统默认的 HTTPS 客户端中。
// 在 scratch 容器等无系统 CA 池的环境下提供基本的 TLS 验证能力。
func init() {
	pool, err := x509.SystemCertPool()
	if err != nil {
		// scratch 容器没有系统 CA，创建空池
		pool = x509.NewCertPool()
	}

	if !pool.AppendCertsFromPEM([]byte(extraCAs)) {
		log.Printf("warning: no extra CA certs loaded")
	}

	http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{
		MinVersion: tls.VersionTLS12,
		RootCAs:    pool,
	}
}
